### ISSUE TITLE
Data export script for Data Explorer Viz Module

### ISSUE THREAD

**Issue by cgettings** [nycehs/NeighborhoodReports#7]
The data export script for the data explorer viz module should produce a .json file for each indicator, with fields for `MeasureID`, `MeasurementType`, `Time`, `GeoType`, `GeoID`, `Value`, `Note`, and `CI` (if present). They should be named [indicatorID].json.

**Comment by mmontesanonyc** [comment]
- MeasureID
- Year: change to Time
- GeoType 
- GeoID
- Value
- Note - actual notes field associated with data points
- MeasureName - Indicator short name + measurement type
- MeasurementType
- CI

**Comment by cgettings** [comment]
Re: flagging values with asterisks: The neighborhood reports data handles this by having a `data_value_geo_entity` character field for display and an `unmodified_data_value_geo_entity` numeric field. So maybe we need a `DisplayValue` field as well?
